name: deploy-container
on:
    push:
        branches:
            -master
            -main
        paths:
            - 'moduleFederation_React/container/**'
defaults:
    run:
        working-directory: moduleFederation_React/container

jobs:
    build:
        runs-on: ubuntu-latest # setting OS of the vm
        steps:
            - uses: actions/checkout@v2 # Checkout to branch
            - run: npm install # install dependencies in the VM
            -run: npm run build # build project in VM

            -uses: ${{ secrets.AWS_USER }}@action-aws-cli@v1.1 # login to AWS account using given credentials in github
            -run: aws s3 sync dist s://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
            env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}